### ISSUE TITLE
Plugin does crash in FL Studio

### ISSUE THREAD

**Issue by michael02022** [prof-spock/FluidSynthPlugin#13] opened 2024-04-21 17:32 UTC
It loads the SF2 file but when pressing a note it freezes the entire DAW or closes it. Not sure if the issue is in the DAW or in the plugin, but it would be good to verify and test the plugin with other DAWs so I leave here the report of it.

On the other side, it works fine in Reaper.

**Comment by prof-spock** [comment] 2024-04-21 21:50
Hello michael02022,

thanks for the information!

For me it is a bit hard to reproduce that because you neither gave me information about the FL Studio version, your operating system nor the version of FluidSynthPlugin or the soundfont used.

What I did test is both Reaper 7.1.4 and Tracktion Waveform 13 for Windows 10, Reaper for MacOS 10.15 and Ubuntu 23. There were no serious issues with the current FluidSynthPlugin version.

Unfortunately I cannot test FL Studio, because their realistic versions are not free, so I have no access to it.

Maybe you can give me some more information on your settings?

Best regards,
Prof. Spock

**Comment by michael02022** [comment] 2024-04-23 00:05
Sure. And thank you for the plugin!
In my case, FL Studio 20.8.4 - Windows 10 Pro (Freezes)
Another friend: FL Studio 21.2.3 - Windows 10 Pro (Closes the DAW)
And another user: FL Studio 21.1 - Windows 11 (Closes the DAW)

**Comment by prof-spock** [comment] 2024-05-01 18:39
Hello michael02022,

sorry I have no perfect solution, but at least a workaround.

I must apologise, but testing was not easy as I do not own an FL Studio licence and was not willing to invest 100€ just for testing. For this reason I'm a bit annoyed that Image-Line doesn't provide at least a minimal application for testing instead of a very stripped down version. In addition, the information in the application forums is unfortunately only accessible to registered users. This makes the search for hints somewhat complicated.

In my opinion, there seems to be a problem in the interaction between FL Studio and the JUCE VST3 wrapper around the FluidSynth plugin; the crash occurs there.  And as mentioned, the plugin works without problems in MuseScore, Tracktion and Reaper.

The workaround is as follows:

- Set the flag `Make Bridged` in the plugin settings `Processing` (see attached figure).
![FLStudio-settings_1](https://github.com/prof-spock/FluidSynthPlugin/assets/26121888/5c33a29f-e3cf-4198-b228-e514b6cce831)
- Set the flag `Use fixed size buffers` in the plugin settings `Troubleshooting` (see attached figure).
![FLStudio-settings_2](https://github.com/prof-spock/FluidSynthPlugin/assets/26121888/f46190ef-4fd0-4c01-80b0-6f8b6bae79d9)

Now the plugin should work fine; I've tested it with a standard General Midi soundfont.
![FLStudio-pluginSettings](https://github.com/prof-spock/FluidSynthPlugin/assets/26121888/abbb7495-52e2-4d11-8760-c99b1d5438a8)

Please have a look and let me know if it does not work!

Best regards,
Prof. Spock

**Comment by prof-spock** [comment] 2024-05-02 17:41
The problem will be fixed in the upcoming release.
FL Studio requires the setting of the audio bus layout and cannot cope with the default JUCE settings (as others DAWs do).

**Comment by michael02022** [comment] 2024-05-02 18:11
Thank you very much for your support! I'm pretty sure people will appreciated it.

**Comment by michael02022** [comment] 2024-05-02 18:17
And last note, it works now! Thanks.

**Closed as completed** 2024-05-02 18:22 UTC
