### ISSUE TITLE
upgrade to FluidSynth 2.3.6 to avoid broken chorus bug in Windows

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#19] opened 2024-08-08 05:42 UTC
Currently, the Chorus effect in FluidSynth plugin does not sound correct in Windows. This is [due to a bug](https://github.com/FluidSynth/fluidsynth/issues/1331) in recent released binaries of FluidSynth, but is now fixed in [FluidSynth 2.3.6](https://github.com/FluidSynth/fluidsynth/releases).

The workaround in the meantime is to manually replace the plugin's copy of `libfluidsynth-3.dll` with the version included with the FluidSynth 2.3.6 Windows release.

**Comment by prof-spock** [comment] 2024-08-10 21:44
Hello mrbumpy409,

great that the simple library replacement works as intended.  This FluidSynth bug seems very tricky.

This is a good example that using dynamically linked libraries has been a good idea... (although your issue #15 might give another impression).

I shall update all distributions once I have rectified the dynamic library issue mentioned above.

Best regards,
Prof. Spock

**Comment by prof-spock** [comment] 2024-11-24 23:24
Hello mrbumpy409,

the new release v0.7.5 provides the fluidsynth library 2.4.0 (at least for Windows and MacOSX, see your issue #17), so the broken chorus should be fixed now.

Please let me know, whether this is correct or not.

Best regards,
Prof. Spock

**Closed as completed** 2024-12-16 12:14 UTC
